### ISSUE TITLE
Add option to run a preconfigured Docker Image to bypass all of the DNF mock installation

### ISSUE THREAD

**Issue by bschonec** [jw3/mock-rpm#4]
It takes quite a bit of time and bandwidth to [install mock](https://github.com/jw3/mock-rpm/blob/master/action.yml#L36).  Could this action be updated so that it could use a pre-configured Docker image with the mock stuff already installed so that all of the repetitive downloads aren't necessary?  I've got several, very small SPEC files that take about 10 seconds to build but it takes about three minutes just to build the mock environment.  The vast majority of this time is [initializing the mock environment](https://github.com/jw3/mock-rpm/blob/master/action.yml#L40).

Perhaps [fedora:latest](https://github.com/jw3/mock-rpm/blob/master/action.yml#L36) could be a variable and then logic surrounding the initialization and configuration of mock could be bypassed in the event that (for example) ${mock_container} is defined.

**Comment by jw3** [comment]
Yeah, #3 is for solving this same problem with a GitHub cache solution. Your alternative solution of using a prebuilt image would be welcomed.

**Comment by bschonec** [comment]
My very amateur testing on a Docker image with  mock preinstalled and 'mock -r fedora-39-x86_64 --init' already run decreases the run time from about 4 minutes to just over 1 minutes.
